#pragma once
#include "all_modules.h"
#include "my_modules.h"
#include "pw_modules.h"

extern PLIST_ENTRY LogonSessionList;
extern PULONG LogonSessionListCount;

PVOID my_m_modules_utils_pFromLinkedListByLuid(PPW_M_MEMORY_ADDRESS pSecurityStruct, ULONG LUIDoffset, PLUID luidToFind);
PVOID my_m_modules_utils_pFromAVLByLuid(PPW_M_MEMORY_ADDRESS pTable, ULONG LUIDoffset, PLUID luidToFind);
PVOID my_m_modules_utils_pFromAVLByLuidRec(PPW_M_MEMORY_ADDRESS pTable, ULONG LUIDoffset, PLUID luidToFind);

BOOL my_m_modules_utils_search(PMY_M_MODULES_CONTEXT cLs, PMY_M_MODULES_LIB pLib);
BOOL my_m_modules_utils_search_generic(PMY_M_MODULES_CONTEXT cLs, PMY_M_MODULES_LIB pLib, PPW_M_PATCH_GENERIC generics, SIZE_T cbGenerics, PVOID * genericPtr, PVOID * genericPtr1, PVOID * genericPtr2, PLONG genericOffset1);

typedef struct _MPW_MSV1_0_PRIMARY_CREDENTIALS {
	struct _MPW_MSV1_0_PRIMARY_CREDENTIALS *next;
	ANSI_STRING Primary;
	LSA_UNICODE_STRING Credentials;
} MPW_MSV1_0_PRIMARY_CREDENTIALS, *PMPW_MSV1_0_PRIMARY_CREDENTIALS;

typedef struct _MPW_MSV1_0_CREDENTIALS {
	struct _MPW_MSV1_0_CREDENTIALS *next;
	DWORD AuthenticationPackageId;
	PMPW_MSV1_0_PRIMARY_CREDENTIALS PrimaryCredentials;
} MPW_MSV1_0_CREDENTIALS, *PMPW_MSV1_0_CREDENTIALS;

typedef struct _MPW_MSV1_0_LIST_51 {
	struct _MPW_MSV1_0_LIST_51 *Flink;
	struct _MPW_MSV1_0_LIST_51 *Blink;
	LUID LocallyUniqueIdentifier;
	LSA_UNICODE_STRING UserName;
	LSA_UNICODE_STRING Domaine;
	PVOID unk0;
	PVOID unk1;
	PSID  pSid;
	ULONG LogonType;
	ULONG Session;
	LARGE_INTEGER LogonTime; 
	LSA_UNICODE_STRING LogonServer;
	PMPW_MSV1_0_CREDENTIALS Credentials;
	ULONG unk19;
	PVOID unk20;
	PVOID unk21;
	PVOID unk22;
	ULONG unk23;
	PVOID CredentialManager;
} MPW_MSV1_0_LIST_51, *PMPW_MSV1_0_LIST_51;

typedef struct _MPW_MSV1_0_LIST_52 {
	struct _MPW_MSV1_0_LIST_52 *Flink;
	struct _MPW_MSV1_0_LIST_52 *Blink;
	LUID LocallyUniqueIdentifier;
	LSA_UNICODE_STRING UserName;
	LSA_UNICODE_STRING Domaine;
	PVOID unk0;
	PVOID unk1;
	PSID  pSid;
	ULONG LogonType;
	ULONG Session;
	LARGE_INTEGER LogonTime; 
	LSA_UNICODE_STRING LogonServer;
	PMPW_MSV1_0_CREDENTIALS Credentials;
	ULONG unk19;
	PVOID unk20;
	PVOID unk21;
	ULONG unk22;
	PVOID CredentialManager;
} MPW_MSV1_0_LIST_52, *PMPW_MSV1_0_LIST_52;

typedef struct _MPW_MSV1_0_LIST_60 {
	struct _MPW_MSV1_0_LIST_6 *Flink;
	struct _MPW_MSV1_0_LIST_6 *Blink;
	PVOID unk0;
	ULONG unk1;
	PVOID unk2;
	ULONG unk3;
	ULONG unk4;
	ULONG unk5;
	HANDLE hSemaphore6;
	PVOID unk7;
	HANDLE hSemaphore8;
	PVOID unk9;
	PVOID unk10;
	ULONG unk11;
	ULONG unk12;
	PVOID unk13;
	LUID LocallyUniqueIdentifier;
	LUID SecondaryLocallyUniqueIdentifier;
	LSA_UNICODE_STRING UserName;
	LSA_UNICODE_STRING Domaine;
	PVOID unk14;
	PVOID unk15;
	PSID  pSid;
	ULONG LogonType;
	ULONG Session;
	LARGE_INTEGER LogonTime; 
	LSA_UNICODE_STRING LogonServer;
	PMPW_MSV1_0_CREDENTIALS Credentials;
	ULONG unk19;
	PVOID unk20;
	PVOID unk21;
	PVOID unk22;
	ULONG unk23;
	PVOID CredentialManager;
} MPW_MSV1_0_LIST_60, *PMPW_MSV1_0_LIST_60;

typedef struct _MPW_MSV1_0_LIST_61 {
	struct _MPW_MSV1_0_LIST_6 *Flink;
	struct _MPW_MSV1_0_LIST_6 *Blink;
	PVOID unk0;
	ULONG unk1;
	PVOID unk2;
	ULONG unk3;
	ULONG unk4;
	ULONG unk5;
	HANDLE hSemaphore6;
	PVOID unk7;
	HANDLE hSemaphore8;
	PVOID unk9;
	PVOID unk10;
	ULONG unk11;
	ULONG unk12;
	PVOID unk13;
	LUID LocallyUniqueIdentifier;
	LUID SecondaryLocallyUniqueIdentifier;
	LSA_UNICODE_STRING UserName;
	LSA_UNICODE_STRING Domaine;
	PVOID unk14;
	PVOID unk15;
	PSID  pSid;
	ULONG LogonType;
	ULONG Session;
	LARGE_INTEGER LogonTime; 
	LSA_UNICODE_STRING LogonServer;
	PMPW_MSV1_0_CREDENTIALS Credentials;
	PVOID unk19;
	PVOID unk20;
	PVOID unk21;
	ULONG unk22;
	PVOID CredentialManager;
} MPW_MSV1_0_LIST_61, *PMPW_MSV1_0_LIST_61;

typedef struct _MPW_MSV1_0_LIST_61_ANTI_mypw {
	struct _MPW_MSV1_0_LIST_61_ANTI_mypw *Flink;
	struct _MPW_MSV1_0_LIST_61_ANTI_mypw *Blink;
	PVOID unk0;
	ULONG unk1;
	PVOID unk2;
	ULONG unk3;
	ULONG unk4;
	ULONG unk5;
	HANDLE hSemaphore6;
	PVOID unk7;
	HANDLE hSemaphore8;
	PVOID unk9;
	PVOID unk10;
	ULONG unk11;
	ULONG unk12;
	PVOID unk13;
	LUID LocallyUniqueIdentifier;
	LUID SecondaryLocallyUniqueIdentifier;
	BYTE waza[12]; 
	LSA_UNICODE_STRING UserName;
	LSA_UNICODE_STRING Domaine;
	PVOID unk14;
	PVOID unk15;
	PSID  pSid;
	ULONG LogonType;
	ULONG Session;
	LARGE_INTEGER LogonTime; 
	LSA_UNICODE_STRING LogonServer;
	PMPW_MSV1_0_CREDENTIALS Credentials;
	PVOID unk19;
	PVOID unk20;
	PVOID unk21;
	ULONG unk22;
	PVOID CredentialManager;
} MPW_MSV1_0_LIST_61_ANTI_mypw, *PMPW_MSV1_0_LIST_61_ANTI_mypw;

typedef struct _MPW_MSV1_0_LIST_62 {
	struct _MPW_MSV1_0_LIST_62 *Flink;
	struct _MPW_MSV1_0_LIST_62 *Blink;
	PVOID unk0;
	ULONG unk1;
	PVOID unk2;
	ULONG unk3;
	ULONG unk4;
	ULONG unk5;
	HANDLE hSemaphore6;
	PVOID unk7;
	HANDLE hSemaphore8;
	PVOID unk9;
	PVOID unk10;
	ULONG unk11;
	ULONG unk12;
	PVOID unk13;
	LUID LocallyUniqueIdentifier;
	LUID SecondaryLocallyUniqueIdentifier;
	LSA_UNICODE_STRING UserName;
	LSA_UNICODE_STRING Domaine;
	PVOID unk14;
	PVOID unk15;
	LSA_UNICODE_STRING Type;
	PSID  pSid;
	ULONG LogonType;
	PVOID unk18;
	ULONG Session;
	LARGE_INTEGER LogonTime; 
	LSA_UNICODE_STRING LogonServer;
	PMPW_MSV1_0_CREDENTIALS Credentials;
	PVOID unk19;
	PVOID unk20;
	PVOID unk21;
	ULONG unk22;
	ULONG unk23;
	ULONG unk24;
	ULONG unk25;
	ULONG unk26;
	PVOID unk27;
	PVOID unk28;
	PVOID unk29;
	PVOID CredentialManager;
} MPW_MSV1_0_LIST_62, *PMPW_MSV1_0_LIST_62;

typedef struct _MPW_MSV1_0_LIST_63 {
	struct _MPW_MSV1_0_LIST_63 *Flink;	
	struct _MPW_MSV1_0_LIST_63 *Blink; 
	PVOID unk0; 
	ULONG unk1; 
	PVOID unk2; 
	ULONG unk3; 
	ULONG unk4; 
	ULONG unk5; 
	HANDLE hSemaphore6; 
	PVOID unk7; 
	HANDLE hSemaphore8; 
	PVOID unk9; 
	PVOID unk10; 
	ULONG unk11;
	ULONG unk12; 
	PVOID unk13; 
	LUID LocallyUniqueIdentifier;
	LUID SecondaryLocallyUniqueIdentifier;
	BYTE waza[12]; 
	LSA_UNICODE_STRING UserName;
	LSA_UNICODE_STRING Domaine;
	PVOID unk14;
	PVOID unk15;
	LSA_UNICODE_STRING Type;
	PSID  pSid;
	ULONG LogonType;
	PVOID unk18;
	ULONG Session;
	LARGE_INTEGER LogonTime; 
	LSA_UNICODE_STRING LogonServer;
	PMPW_MSV1_0_CREDENTIALS Credentials;
	PVOID unk19;
	PVOID unk20;
	PVOID unk21;
	ULONG unk22;
	ULONG unk23;
	ULONG unk24;
	ULONG unk25;
	ULONG unk26;
	PVOID unk27;
	PVOID unk28;
	PVOID unk29;
	PVOID CredentialManager;
} MPW_MSV1_0_LIST_63, *PMPW_MSV1_0_LIST_63;